import type { Firestore } from 'firebase-admin/firestore';
import { z } from 'zod';
import { logger } from '../logger.js';
import { getLLMProvider, LLMProviderError, type LLMProvider } from '../providers/index.js';
import { getPlan, patchPlan } from '../db/plans.js';
import { listScenes, patchScene } from '../db/scenes.js';
import { getSelectedHookDraft } from '../db/hook-drafts.js';
import {
  isAllowedPlanTransition,
  type Plan,
  type Scene,
} from '../db/schemas.js';
import {
  getNeurocoreClient,
  NeurocoreError,
  type MemoryContextResponse,
  type NeurocoreClient,
} from '../neurocore/index.js';
import { extractJson } from './json-utils.js';
import { PlanningEngineError } from './errors.js';
import {
  compositionRulesToPrompt,
  getCompositionRules,
  runtimeToWordCount,
  wordBudgetPerScene,
  estimateSceneSeconds,
} from './composition-rules.js';
import { generateScenes, type GenerateScenesResult } from './generate-scenes.js';

/**
 * Call 4 of the four-step pipeline: script writing.
 *
 * Reads the scenes generated by Call 3, pulls Rick's spoken-voice profile
 * (and per-listing insight when contactId is set) via Neurocore, and asks
 * the LLM to write full spoken-word scripts for every scene at once. One
 * LLM call covers the whole video so the model can preserve cross-scene
 * coherence (handoffs, callbacks, total runtime budget).
 *
 * On success, patches each scene with its script + emphasis cues + pacing
 * notes + transition note, updates plan.estimatedRuntimeSeconds from the
 * sum of per-scene estimates, and transitions plan.status → scenes_generated.
 *
 * generatePlanContent() composes Call 3 + Call 4 as the canonical "generate
 * everything" entry point used by the M8 UI's "Generate plan" button.
 */

const STEP_NAME = 'write-scripts';
const MAX_VOICE_CONTEXT_CHARS = 30_000;

// Per-scene script bundle the LLM returns.
const scriptForSceneSchema = z.object({
  sceneId: z.string().min(1),
  script: z.string().min(1),
  emphasisCues: z.array(z.string()).default([]),
  pacingNotes: z.string().default(''),
  transitionNote: z.string().default(''),
});
type ScriptForScene = z.infer<typeof scriptForSceneSchema>;
const scriptsArraySchema = z.array(scriptForSceneSchema).min(1);

interface WriteScriptsOptions {
  provider?: LLMProvider;
  client?: NeurocoreClient;
  db?: Firestore;
  timeoutMs?: number;
}

export interface WriteScriptsResult {
  plan: Plan;
  scenes: Scene[];
  degraded: boolean;
  retried: boolean;
  durationMs: number;
}

export async function writeScripts(
  planId: string,
  opts: WriteScriptsOptions = {},
): Promise<WriteScriptsResult> {
  const t0 = Date.now();
  const provider = opts.provider ?? await getLLMProvider();
  const client = opts.client ?? getNeurocoreClient();

  // ---- Load + validate plan ------------------------------------------
  const plan = await getPlan(planId, opts.db);
  if (!plan) {
    throw new PlanningEngineError(STEP_NAME, 'PLAN_NOT_FOUND', `no plan with id ${planId}`, {
      planId,
    });
  }
  if (!isAllowedPlanTransition(plan.status, 'scenes_generated')) {
    throw new PlanningEngineError(
      STEP_NAME,
      'DISALLOWED_TRANSITION',
      `cannot transition from ${plan.status} to scenes_generated`,
      { planId, detail: { from: plan.status, to: 'scenes_generated' } },
    );
  }

  const scenes = await listScenes(planId, opts.db);
  if (scenes.length === 0) {
    throw new PlanningEngineError(
      STEP_NAME,
      'NO_PROJECT_MATCHES', // reusing code — no scenes means no project work to write about
      'plan has no scenes — run scene generation (Call 3) first',
      { planId },
    );
  }

  // ---- youtube_advanced: require selectedHookVariantId ----------------
  // The transition table should prevent reaching write-scripts without a
  // hook selection on youtube_advanced plans, but enforce it defensively.
  if (plan.type === 'youtube_advanced' && !plan.selectedHookVariantId) {
    throw new PlanningEngineError(
      STEP_NAME,
      'DISALLOWED_TRANSITION',
      'youtube_advanced plan reached write-scripts without a selected hook variant — run hook generation and selection first (plans must transition through hooks_generated → hook_selected before scenes_generated)',
      { planId },
    );
  }

  // ---- Fetch selected hook (youtube_advanced only) --------------------
  let selectedHook: import('../db/schemas.js').HookDraft | null = null;
  if (plan.type === 'youtube_advanced' && plan.selectedHookVariantId) {
    selectedHook = await getSelectedHookDraft(planId, opts.db);
  }

  // ---- Pull voice profile from Neurocore ------------------------------
  let context: MemoryContextResponse;
  try {
    context = await client.getVoiceProfile({
      planMode: plan.type,
      ...(plan.sourceListingId ? { contactId: plan.sourceListingId } : {}),
      jobContextHint: plan.title,
    });
  } catch (err) {
    if (err instanceof NeurocoreError) {
      throw new PlanningEngineError(
        STEP_NAME,
        'LLM_FAILED',
        `neurocore unreachable: ${err.message}`,
        { planId, detail: { neurocoreCode: err.code } },
      );
    }
    throw err;
  }
  const voiceBlock = context.systemBlock.slice(0, MAX_VOICE_CONTEXT_CHARS);

  // ---- Build prompt and call LLM -------------------------------------
  const basePrompt = buildPrompt(plan, scenes, voiceBlock, selectedHook);
  let retried = false;
  let scripts: ScriptForScene[];

  try {
    const raw = await invokeLLM(provider, basePrompt, opts.timeoutMs);
    const parsed = tryParseScripts(raw, scenes);
    if (parsed.ok) {
      scripts = parsed.value;
    } else {
      retried = true;
      const stricter = `${basePrompt}\n\nIMPORTANT: Your previous response was not parseable OR did not cover every sceneId. Respond with ONLY a JSON array of script objects — one per scene, by id — no fences, no prose. Start with [ and end with ].`;
      const raw2 = await invokeLLM(provider, stricter, opts.timeoutMs);
      const parsed2 = tryParseScripts(raw2, scenes);
      if (!parsed2.ok) {
        throw new PlanningEngineError(
          STEP_NAME,
          'INVALID_OUTPUT',
          `LLM output did not parse as full script set after retry: ${parsed2.reason}`,
          { planId, detail: parsed2.detail },
        );
      }
      scripts = parsed2.value;
    }
  } catch (err) {
    if (err instanceof PlanningEngineError) throw err;
    if (err instanceof LLMProviderError) {
      throw new PlanningEngineError(
        STEP_NAME,
        'LLM_FAILED',
        `${err.providerName} CLI failed: ${err.message}`,
        { planId, detail: { providerCode: err.code } },
      );
    }
    throw err;
  }

  // ---- For youtube_advanced: override scene 1 script with hook.scriptText
  // The LLM was told not to regenerate scene 1, but we enforce it verbatim
  // by replacing whatever the LLM emitted for scene 1.
  if (selectedHook && scenes.length > 0) {
    const scene1 = scenes.find((s) => s.order === 1) ?? scenes[0]!;
    const hookScriptIdx = scripts.findIndex((s) => s.sceneId === scene1.id);
    if (hookScriptIdx >= 0) {
      scripts[hookScriptIdx] = {
        ...scripts[hookScriptIdx]!,
        script: selectedHook.scriptText,
      };
    }
  }

  // ---- Persist scripts on each scene + transition plan ----------------
  let totalSeconds = 0;
  const updatedScenes: Scene[] = [];
  try {
    for (const s of scripts) {
      const estDur = estimateSceneSeconds(s.script);
      totalSeconds += estDur;
      const updated = await patchScene(
        planId,
        s.sceneId,
        {
          script: s.script,
          scriptDraft: s.script,
          emphasisCues: s.emphasisCues,
          pacingNotes: s.pacingNotes,
          transitionNote: s.transitionNote,
          estimatedDurationSeconds: estDur,
        },
        opts.db,
      );
      if (updated) updatedScenes.push(updated);
    }
  } catch (err) {
    throw new PlanningEngineError(
      STEP_NAME,
      'PERSIST_FAILED',
      `failed to persist scripts: ${(err as Error).message}`,
      { planId },
    );
  }

  let updatedPlan: Plan | null;
  try {
    updatedPlan = await patchPlan(
      planId,
      {
        status: 'scenes_generated',
        estimatedRuntimeSeconds: totalSeconds,
      },
      opts.db,
    );
  } catch (err) {
    throw new PlanningEngineError(
      STEP_NAME,
      'PERSIST_FAILED',
      `failed to transition plan status: ${(err as Error).message}`,
      { planId },
    );
  }
  if (!updatedPlan) {
    throw new PlanningEngineError(STEP_NAME, 'PLAN_NOT_FOUND', 'plan disappeared during script writing', {
      planId,
    });
  }

  const durationMs = Date.now() - t0;
  logger.info(
    {
      planId,
      sceneCount: updatedScenes.length,
      estimatedRuntimeSeconds: totalSeconds,
      targetRuntimeSeconds: plan.targetRuntimeSeconds,
      retried,
      degraded: context.metadata.degraded,
      durationMs,
    },
    'script writing complete',
  );
  return {
    plan: updatedPlan,
    scenes: updatedScenes,
    degraded: context.metadata.degraded,
    retried,
    durationMs,
  };
}

/**
 * Composite entry point: run Call 3 then Call 4 in sequence. The UI's
 * "Generate plan" button hits this. If scenes already exist (e.g. Rick
 * re-runs after a Call 4 failure), pass `skipScenes: true` to only retry
 * script writing.
 */
export async function generatePlanContent(
  planId: string,
  opts: WriteScriptsOptions & { skipScenes?: boolean } = {},
): Promise<{
  scenesResult: GenerateScenesResult | null;
  scriptsResult: WriteScriptsResult;
}> {
  const scenesResult = opts.skipScenes
    ? null
    : await generateScenes(planId, {
        ...(opts.provider !== undefined ? { provider: opts.provider } : {}),
        ...(opts.db !== undefined ? { db: opts.db } : {}),
        ...(opts.timeoutMs !== undefined ? { timeoutMs: opts.timeoutMs } : {}),
      });
  const scriptsResult = await writeScripts(planId, opts);
  return { scenesResult, scriptsResult };
}

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

const DEFAULT_WORDS_PER_MINUTE = 150;

function buildPrompt(
  plan: Plan,
  scenes: Scene[],
  voiceBlock: string,
  selectedHook?: import('../db/schemas.js').HookDraft | null,
): string {
  // youtube_advanced uses the format-profile registry for composition rules
  // (not v1 CompositionRules). For the word-budget calculations we use the
  // default wpm since the format-profile wpm lives in FormatProfile.pacingRules.
  const isV2 = plan.type === 'youtube_advanced';
  const wpm = isV2
    ? DEFAULT_WORDS_PER_MINUTE
    : getCompositionRules(plan.type).wordsPerMinute;
  const totalWords = runtimeToWordCount(plan.targetRuntimeSeconds, wpm);
  const perScene = wordBudgetPerScene(totalWords, scenes.length);

  const compositionBlock = isV2
    ? `MODE: youtube_advanced\nWrite in Rick's spoken voice — conversational, direct, technically authoritative.`
    : compositionRulesToPrompt(getCompositionRules(plan.type));

  const sceneList = scenes
    .map((s) => {
      return [
        `Scene ${s.order} — id: ${s.id}`,
        `  Title: ${s.title}`,
        `  Description: ${s.description}`,
        `  Framing: ${s.framingNotes}`,
        s.projectRef ? `  Featuring project: ${s.projectRef}` : null,
      ]
        .filter(Boolean)
        .join('\n');
    })
    .join('\n\n');

  const hookNote = selectedHook
    ? `\nHOOK VARIANT (scene 1 is already written — Rick chose this hook):\nArchetype: ${selectedHook.archetype}\nScene 1's script has ALREADY been written (Rick chose a hook variant: '${selectedHook.archetype}'). Reference scene 1 in your transitions but DO NOT regenerate scene 1's script.\n`
    : '';

  return `You are writing the full SPOKEN-WORD SCRIPTS for every scene of a video Rick is about to record. The scene cards (what to show, framing) are already locked. Your job is to write what Rick will SAY for each scene, in Rick's voice.

${compositionBlock}

VOICE CONTEXT (from Neurocore — Rick's spoken-voice fingerprint, profile, and any listing insight):

${voiceBlock}
${hookNote}
TARGET TOTAL RUNTIME: ${plan.targetRuntimeSeconds}s  (~${totalWords} words of spoken text across all scenes)
WORDS PER SCENE TARGET: ~${perScene} words (you may vary scene-to-scene — opening/closing are usually shorter)

OUTPUT FORMAT:
A single JSON array — one element per scene, in scene-id order. Each element matches:
{
  "sceneId": "<the exact id from the scene list below>",
  "script": "<full spoken text Rick will read aloud — complete sentences, no bullet points, no stage directions inline>",
  "emphasisCues": ["<word or short phrase to stress>", ...],
  "pacingNotes": "<1-2 sentences telling Rick how to pace this scene — where to slow down, where to keep tempo>",
  "transitionNote": "<one sentence telling Rick how to bridge to the next scene>"
}

RULES:
- Output ONE element per scene, by id. Do not skip scenes. Do not invent scenes.
- script is what Rick literally says out loud. Plain prose. No "[show dashboard]" stage directions in the script — those live in framingNotes, which is fixed.
- Script density across all scenes should land within ±15% of ${totalWords} words.
- Write in spoken register: shorter sentences than written prose, conversational transitions, occasional rhetorical asides — match the <voice> / <spokenVoice> guidance in the voice context.
- Avoid anti-patterns. Especially: no "Hey guys", no "Hi I'm Rick excited to apply", no "today I want to talk about".
- Output JSON ONLY. No fences. No prose. Start with [ and end with ].

SCENES TO WRITE SCRIPTS FOR (script length budget: ~${perScene} words each):

${sceneList}`;
}

async function invokeLLM(
  provider: LLMProvider,
  prompt: string,
  timeoutMs: number | undefined,
): Promise<string> {
  return provider.generate(prompt, timeoutMs !== undefined ? { timeoutMs } : undefined);
}

type ParseOutcome =
  | { ok: true; value: ScriptForScene[] }
  | { ok: false; reason: string; detail: unknown };

function tryParseScripts(raw: string, scenes: Scene[]): ParseOutcome {
  let parsed: unknown;
  try {
    parsed = JSON.parse(extractJson(raw));
  } catch (err) {
    return { ok: false, reason: 'not valid JSON', detail: (err as Error).message };
  }
  const validated = scriptsArraySchema.safeParse(parsed);
  if (!validated.success) {
    return {
      ok: false,
      reason: 'JSON parsed but failed schema validation',
      detail: validated.error.issues,
    };
  }
  // Every scene must be covered. Extra scriptedIds get discarded silently.
  const sceneIds = new Set(scenes.map((s) => s.id));
  const covered = new Set(validated.data.map((s) => s.sceneId).filter((id) => sceneIds.has(id)));
  if (covered.size !== sceneIds.size) {
    const missing = [...sceneIds].filter((id) => !covered.has(id));
    return {
      ok: false,
      reason: `missing scripts for sceneIds: ${missing.join(', ')}`,
      detail: { missing },
    };
  }
  // Filter to only known sceneIds (in case the model emitted phantoms).
  return { ok: true, value: validated.data.filter((s) => sceneIds.has(s.sceneId)) };
}

export const _internal = {
  buildPrompt,
  tryParseScripts,
};
