import type { Firestore } from 'firebase-admin/firestore';
import { getDb } from './firestore.js';
import { makeId } from './ids.js';
import {
  hookDraftSchema,
  type HookDraft,
  type HookDraftCreate,
} from './schemas.js';
import { deleteAllMatching } from './batch-utils.js';

/**
 * HookDraft CRUD — subcollection under each Plan (plans/{planId}/hook_drafts).
 * One Plan typically has 3-4 drafts at a time, generated by Call 5 in the
 * v2 pipeline. Selection is atomic (batch-flip).
 */

const PLANS = 'plans';
const HOOK_DRAFTS = 'hook_drafts';

function tsToDate(v: unknown): Date {
  if (v instanceof Date) return v;
  const maybe = v as { toDate?: () => Date };
  return typeof maybe?.toDate === 'function' ? maybe.toDate() : new Date(0);
}

function docToHook(id: string, data: Record<string, unknown>): HookDraft {
  return hookDraftSchema.parse({
    id,
    archetype: data.archetype,
    scriptText: data.scriptText,
    predictedRetention: data.predictedRetention,
    selected: data.selected ?? false,
    createdAt: tsToDate(data.createdAt),
  });
}

function hooksCol(db: Firestore, planId: string) {
  return db.collection(PLANS).doc(planId).collection(HOOK_DRAFTS);
}

export async function createHookDraft(
  planId: string,
  input: HookDraftCreate,
  db: Firestore = getDb(),
): Promise<HookDraft> {
  const id = makeId('hook');
  const doc = {
    archetype: input.archetype,
    scriptText: input.scriptText,
    predictedRetention: input.predictedRetention,
    selected: input.selected ?? false,
    createdAt: new Date(),
  };
  await hooksCol(db, planId).doc(id).set(doc);
  return docToHook(id, doc);
}

export async function listHookDraftsForPlan(
  planId: string,
  db: Firestore = getDb(),
): Promise<HookDraft[]> {
  const snap = await hooksCol(db, planId).orderBy('createdAt', 'asc').get();
  return snap.docs.map((d) => docToHook(d.id, d.data() as Record<string, unknown>));
}

export async function getSelectedHookDraft(
  planId: string,
  db: Firestore = getDb(),
): Promise<HookDraft | null> {
  const snap = await hooksCol(db, planId).where('selected', '==', true).limit(1).get();
  if (snap.empty) return null;
  const doc = snap.docs[0]!;
  return docToHook(doc.id, doc.data() as Record<string, unknown>);
}

export async function setSelectedHookDraft(
  planId: string,
  hookId: string,
  db: Firestore = getDb(),
): Promise<void> {
  const target = await hooksCol(db, planId).doc(hookId).get();
  if (!target.exists) {
    throw new Error(`HookDraft ${hookId} not found under plan ${planId}`);
  }
  const all = await hooksCol(db, planId).get();
  const batch = db.batch();
  for (const d of all.docs) {
    batch.update(d.ref, { selected: d.id === hookId });
  }
  await batch.commit();
}

/**
 * Flip the selection flags AND apply the plan update in a single atomic batch,
 * so the hook subcollection and `plan.selectedHookVariantId`/status can never
 * desync on a mid-operation failure. `planUpdate` is written onto the plan doc
 * verbatim (the caller is responsible for having validated any status
 * transition first). Returns nothing; throws if the target hook is missing.
 */
export async function setSelectedHookDraftWithPlanUpdate(
  planId: string,
  hookId: string,
  planUpdate: Record<string, unknown>,
  db: Firestore = getDb(),
): Promise<void> {
  const all = await hooksCol(db, planId).get();
  if (!all.docs.some((d) => d.id === hookId)) {
    throw new Error(`HookDraft ${hookId} not found under plan ${planId}`);
  }
  const batch = db.batch();
  for (const d of all.docs) {
    batch.update(d.ref, { selected: d.id === hookId });
  }
  batch.update(db.collection(PLANS).doc(planId), planUpdate);
  await batch.commit();
}

export async function deleteAllHookDraftsForPlan(
  planId: string,
  db: Firestore = getDb(),
): Promise<number> {
  // Drained in chunks so >500 drafts are fully removed (no silent orphans).
  return deleteAllMatching(hooksCol(db, planId), db);
}
